### ISSUE TITLE
I get a NoMethodError: undefined method `acts_as_list' when trying to include acts_as_list

### ISSUE THREAD

**Issue by bo-oz** [swanandp/acts_as_list#176] opened 2015-12-03 18:33 UTC
I just installed the gem and called the acts_as_list method in my model (including :scope), but somehow I keep getting the error message I mentioned in the subject. Is something broken maybe?

**Comment by fabn** [comment] 2015-12-16 16:18
Could you provide a stack trace for your error?

**Comment by fabn** [comment] 2015-12-16 16:19
Also versions for both active_record and acts_as_list.

**Comment by GinBlades** [comment] 2016-01-25 15:56
I'm having a similar issue, but it is happening when using acts_as_list from a gem. [This StackOverflow question](http://stackoverflow.com/questions/34816558/ruby-gem-dependency-loading) explains my issue. I am putting models that will be shared across multiple rails projects into a gem. When I use `acts_as_list` from the gem console, it works as expected. When I try to load the console from the Rails project that includes my gem(that uses acts_as_list), I get a `NoMethodError`.

    /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing': unde
    fined method `acts_as_list' for #<Class:0x0055ded992ae88>
    Did you mean?  acts_as_tree (NoMethodError)
    from /home/user/sites/demo/domain/lib/domain/models/page.rb:34:in `<class:Page>'
    from /home/user/sites/demo/domain/lib/domain/models/page.rb:5:in `<module:Models>'
    from /home/user/sites/demo/domain/lib/domain/models/page.rb:4:in `<module:Domain>'
    from /home/user/sites/demo/domain/lib/domain/models/page.rb:3:in `<top (required)>'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
    from /home/user/sites/demo/domain/lib/domain.rb:39:in `<top (required)>'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    from /home/user/sites/demo/analyzer/config/application.rb:14:in `<top (required)>'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:82:in `require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:82:in `preload'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/user/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'

I'm using activerecord (= 4.2.5) and acts_as_list (0.7.2). I've also tried including the 'acts_as_list' gem in the Gemfile of the Rails project.

**Comment by orenf** [comment] 2016-01-28 03:41
:+1:

**Comment by orenf** [comment] 2016-01-28 17:33
This is no longer an issue for me.  It was a problem with order in which the initializers where executing. Hope this helps someone else: https://github.com/orenf/spree/commit/bcd1753c8a0a9f2e53655052a411188749d58d79

**Comment by brendon** [comment] 2016-04-17 21:12
Closing this. If anyone is still having the issue please let me know.

**Closed by brendon** 2016-04-17 21:12 UTC
Labels: Need to Verify

**Comment by zedtux** [comment] 2016-11-17 07:42
I am experiencing this issue. I'm using the gem version 0.8.2 in both: the gem and the app.

In the gem, I'm first requiring libraries like `acts_as_list` and then the models, and in the app, I tried multiples cases:

 - Automatically loading from the Gemfile
 - Adding `require 'acts_as_list'` in the model where come from the error
 - Adding `require 'acts_as_list'` in the `config/application.rb` file

None of those fixes the issue.

It's really like the plugin is loaded, but in the way it is working, the `acts_as_list` method is not available in the application models.

**Comment by brendon** [comment] 2016-11-17 08:17
Are you using Rails? If so, you shouldn't have to manually require `acts_as_list`. I'm afraid we'll need more information before we can help. It's likely to be something specific to your configuration.

**Comment by zedtux** [comment] 2016-11-17 09:05
Yes I'm using Rails, and my tries was just to be sure 😉

**Comment by zedtux** [comment] 2016-11-17 09:14
I'll try to give you as much as information as I can, but I'm limited as it is an enterprise application.

So first of all, the gem where the model is using `acts_as_list` has in the gemspec file the following:

```ruby
  ...
  spec.required_ruby_version = '~> 2.0'

  spec.add_dependency 'activerecord', '~> 4.2.7.1'
  spec.add_dependency 'activesupport', '~> 4.2.7.1'
  spec.add_dependency 'iconv', '~> 1.0.4'
  spec.add_dependency 'acts_as_list', '~> 0.8.2'
  ...
```

And the class using `acts_as_list` is like this:

```ruby
class RightPackage < ActiveRecord::Base
  acts_as_list

  # @nodoc ~~~ named scopes ~~~
  scope :sorted, -> { order(:position) }
end
```

The gem is working fine here, I have Rspec and all is passing green.

Then in the application Gemfile I have the following:

```Gemfile
source 'http://gems.xxxxx.com'

# Core libraries
gem 'rails', '4.2.7.1'
gem 'slim-rails'

# Enterprise libraries
gem 'user_management', '~> 2.0.0', path: '/user_management'

...
```

Last but not least, I'm using Docker and docker-compose.

Then I run `docker-compose up` I got the following output:

```
Starting legalannouncements_bundle_1
Starting legalannouncements_web_1
Attaching to legalannouncements_bundle_1, legalannouncements_web_1
bundle_1  | Bundler data container
legalannouncements_bundle_1 exited with code 0
web_1     | Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'user_management'. (Bundler::GemRequireError)
web_1     | Gem Load Error is: undefined local variable or method `acts_as_list' for #<Class:0x005624291d2cb8>
web_1     | Backtrace for gem load error is:
web_1     | /bundle/gems/activerecord-4.2.7.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
web_1     | /user_management/lib/user_management/models/right_package.rb:20:in `<class:RightPackage>'
web_1     | /user_management/lib/user_management/models/right_package.rb:1:in `<top (required)>'
web_1     | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
web_1     | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
web_1     | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
web_1     | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
web_1     | /user_management/lib/user_management.rb:38:in `<top (required)>'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
web_1     | /usr/local/bundle/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
web_1     | /application/config/application.rb:16:in `<top (required)>'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
web_1     | /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
web_1     | /application/bin/rails:9:in `require'
web_1     | /application/bin/rails:9:in `<top (required)>'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
web_1     | /bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
web_1     | /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
web_1     | /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | /application/bin/spring:15:in `<top (required)>'
web_1     | bin/rails:3:in `load'
web_1     | bin/rails:3:in `<main>'
web_1     | Bundler Error Backtrace:
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
web_1     | 	from /application/config/application.rb:16:in `<top (required)>'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
web_1     | 	from /application/bin/rails:9:in `require'
web_1     | 	from /application/bin/rails:9:in `<top (required)>'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
web_1     | 	from /bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
web_1     | 	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | 	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | 	from /application/bin/spring:15:in `<top (required)>'
web_1     | 	from bin/rails:3:in `load'
web_1     | 	from bin/rails:3:in `<main>'
legalannouncements_web_1 exited with code 1
```

**Comment by brendon** [comment] 2016-11-17 19:54
Thanks @zedtux, my guess is that it's to do with the gemspec method of including the library? Perhaps the `require` differs from what happens in bundler? Or perhaps it doesn't happen at all?

Is there a reason why you can't use bundler to specify your dependencies? I've not done what you're doing before. When I've used engines/gems I've just specified all the dependencies in the master application.

**Comment by zedtux** [comment] 2016-11-18 16:04
> Is there a reason why you can't use bundler to specify your dependencies?

Well actually I have the dependencies here because I believed it is the right place to put them all. I can move them to the Gemfile with no problems if it's fixing my issue 😃.

I'll give it a try and let you know.

**Comment by brendon** [comment] 2016-11-20 00:40
Thanks :) That might might work for you I think. Even we specify our dependencies in the gem that way :)

**Comment by zedtux** [comment] 2016-11-21 10:33
@brendon here is the update:

In the gem, which is using `acts_as_list`, I have moved all the dependencies from the gemspec file to the Gemfile as the following:

```ruby
source 'http://gems.company.com'

# Specify your gem's dependencies in user_management.gemspec
gemspec

gem 'activerecord', '~> 4.2.7.1'
gem 'activesupport', '~> 4.2.7.1'
gem 'iconv', '~> 1.0.4'
gem 'acts_as_list', '~> 0.8.2'
...

```

I haven't removed the `require 'acts_as_list'` from the gem, otherwise Rspec is failing with the following:

```bash
`method_missing': undefined local variable or method `acts_as_list' for #<Class:0x007fb84b18cd00> (NameError)
```

Now in the Rails application using the gem, when I try to boot it I go the following output:

```
Starting legalannouncements_bundle_1
Starting legalannouncements_web_1
Attaching to legalannouncements_bundle_1, legalannouncements_web_1
bundle_1  | Bundler data container
legalannouncements_bundle_1 exited with code 0
web_1     | Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
web_1     | /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- acts_as_list (LoadError)
web_1     | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
web_1     | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
web_1     | 	from /bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
web_1     | 	from /user_management/lib/user_management.rb:3:in `<top (required)>'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
web_1     | 	from /usr/local/bundle/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
web_1     | 	from /application/config/application.rb:18:in `<top (required)>'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `require'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
web_1     | 	from /bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
web_1     | 	from /application/bin/rails:9:in `require'
web_1     | 	from /application/bin/rails:9:in `<top (required)>'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
web_1     | 	from /bundle/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
web_1     | 	from /bundle/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
web_1     | 	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | 	from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
web_1     | 	from /application/bin/spring:15:in `<top (required)>'
web_1     | 	from bin/rails:3:in `load'
web_1     | 	from bin/rails:3:in `<main>'
legalannouncements_web_1 exited with code 1
```

**Comment by brendon** [comment] 2016-11-21 21:30
That's pretty strange. I'm still confused as to why you need to require `acts_as_list` given it's already required in `init.rb` and then bootstrapped here: https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list.rb

I think the problem is a bit deeper. Is the gem accessible to to your gem? The error message seems to indicate that it isn't.

I'm not sure what to do from here...

**Comment by zedtux** [comment] 2016-11-22 09:13
_FYI I found [this](http://guides.rubyonrails.org/engines.html#other-gem-dependencies) from the Rails guide. It seems that the gem dependencies (not development one) shouldn't be in the Gemfile but in the gemspec. Also read [Clarifying the Roles of the .gemspec and Gemfile](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)._

Honestly I'm not mastering the loading sequence when building a gem, so I wasn't chocked to be obliged to require an external library when writing a new gem.

> I think the problem is a bit deeper. Is the gem accessible to to your gem?

Running my specs in the gem project is working fine.

To me, the issue is more like in the Rails project, including my gem where I'm using `acts_as_list`, which is requiring the gem but not its dependencies.

**Comment by brendon** [comment] 2016-11-22 21:10
Thanks @zedtux, perhaps we shouldn't have the Gemfile.lock in the gem source? Not sure if this is the cause of the issue. Can you try manually removing it from the gem as installed on your machine and see if that helps. If so, we can remove it from the repo.

The gem works with Rails 4 and 5 and is tested against them across a range of Rubies and databases.

Reading through this: http://guides.rubygems.org/make-your-own-gem/ `init.rb` is probably not used. You could try removing that from your local copy of the gem too to see what happens?

**Comment by zedtux** [comment] 2016-11-25 10:50
@brendon I did some tests and :

 - You do not have the Gemfile.lock in the repository
 - Removing the `init.rb` has no effect (Actually I'm sure you can remove it)
 - My issue is a loading order issue because I have added a `puts` in the `ActiveRecord::Acts::List.included` and when I have the error, the puts doesn't appear, while if I comment the line `acts_as_list` in my model, then I see the puts.

So it's like Rails is trying to access the `acts_as_list` method while ActiveRecord has not be yet finished to load or something similar.

**Comment by zedtux** [comment] 2016-11-25 12:00
The workaround I found is to include the `include ActiveRecord::Acts::List` in my model, like this:

```ruby
class RightPackage < ActiveRecord::Base
  include ActiveRecord::Acts::List

  acts_as_list
end
```

**Comment by brendon** [comment] 2016-11-25 23:42
Hi @zedtux, I'm glad you were able to figure it out! If your model is stored in the engine (gem) but not namespaces (like it doesn't seem to be from your example), perhaps the main rails application initialisation process is attempting to load the model class before the gem has been through its initialisation process.

You could leave your solution as-is, or look at namespacing the model.

Perhaps we could look at an earlier opportunity to inject acts_as_list into active_record?

**Comment by brendon** [comment] 2016-11-26 00:17
@zedtux, I had a look at how the `ancestry` gem loads itself vs `acts_as_list` and there were some notable differences. `ancestry` injects its initialisation method `acts_as_ancestry` straight into `ActiveRecord::Base`.

I've create a branch: https://github.com/swanandp/acts_as_list/tree/Improve-load-method that emulates this method. Try using this branch in your project and let me know the outcome. The tests ran green locally but I'm just waiting for the CI to run to be sure it works across all environments.

**Comment by brendon** [comment] 2016-11-26 03:54
Actually @zedtux, I was happy with the new initialisation method so I've merged it into master and fixed a few tests too. Still let me know how you get on though.

**Comment by jrochkind** [comment] 2016-12-06 19:23
Can you give me a commit sha for "I was happy with the new initialisation method so I've merged it into master and fixed a few tests too", so I can later look to see what future released version includes it?

**Comment by brendon** [comment] 2016-12-06 20:20
Hi @jrochkind, current master is what you want. Here's the SHA of the actual commit: https://github.com/swanandp/acts_as_list/commit/4abf1371b243dbd3d924b74fc073e7da0952edbd

Once @zedtux gets back to me as to whether this fixed his problem, I'll look to release a new gem version.

**Comment by zedtux** [comment] 2016-12-07 07:27
Sorry @brendon I was very busy and forgot about this. I'll check it today.

**Comment by zedtux** [comment] 2016-12-22 14:19
@brendon I'm so sorry for the delay. I just tested and it seems to work! Good job 👍

**Comment by brendon** [comment] 2016-12-22 18:39
Thanks @zedtux :) That's good to hear :)

**Comment by vasilakisfil** [comment] 2019-02-01 10:13
Surprisingly I am also getting the same error, in Rails 5.2.1.1. Had to manually require the gem in application.rb to make it work. Will investigate further to see what's the actual issue.

**Comment by brendon** [comment] 2019-02-01 22:55
Hi @vasilakisfil, yes please do get back to me on that. Generally it's that something is loading your model before the rails app is initialised.
