### ISSUE TITLE
Unexpected behaviour when inserting consecutive items with default positions

### ISSUE THREAD

**Issue by jonasschneider** [swanandp/acts_as_list#124] opened 2014-05-31 22:58 UTC
Environment: Suppose `Item` has `acts_as_list` and a position column with default of 0.
1. Insert an item A into the list. (`a = Item.create!`)
2. Insert another item B into the list. (`b = Item.create!`)

Expected behaviour: `a.position == 1`, `b.position == 2`

Actual behaviour: `a.position == 2`, `b.position == 1`.

I believe the culprit is https://github.com/swanandp/acts_as_list/commit/3ebaffc2680a7ba4ca5bef175e35ab0207e28562. The setting of the top position there is causing the check in `add_to_list_bottom` at https://github.com/swanandp/acts_as_list/blob/3ebaffc2680a7ba4ca5bef175e35ab0207e28562/lib/acts_as_list/active_record/acts/list.rb#L290 to take the wrong branch, and reverse the positions on the items.

Am I missing something here, or is this a bug?

**Comment by brendon** [comment] 2016-04-17 20:55
I thought I had this reproduced, but I couldn't reproduce it. I'm going to close this for now unless someone can provide a test case that shows the bug.

**Closed by brendon** 2016-04-17 20:55 UTC
